#!/bin/sh
#
# script to grab instructions from build server and run them
# this is run from cron under buildagent user
#
# V0.1 - initial kinks worked out 2014-02-01

# cron doesn't put me in my home
cd /home/buildagent
LOG="/home/buildagent/upload-$$.log"

# cron doesn't set up my PATH correctly (can cause mock failure)
PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/buildagent/bin

# don't run if there is something already running
[ -f build-script ] && exit 0

# don't run if the loadavg hits 1 or more
LOADAVG="`cat /proc/loadavg`"
[ "${LOADAVG%%.*}" -lt 1 ] || exit

# don't run if there are lots of uploads pending
UPLOADS="`ls -1 result-*.tgz 2>/dev/null | wc -l`"
[ $UPLOADS -lt 4 ] || exit

# get the MAC address
# this really could be any uniqueid, wouldn't have to be MAC
HWADDR="`ifconfig |fgrep HWaddr |head -1 |tr -d ':'`"
AGENTID="${HWADDR#*HWaddr }"
AGENTID="${AGENTID:0:12}"
[ -z "$AGENTID" ] && exit

# download a job script
wget -qSO build-script --header="X-Agent-ID: $AGENTID" http://build.pennyos.org/getjob.php 2> build-script-header >>$LOG 

# if download didn't succeed (will give 404 if nothing to do), stop
if [ $? -ne 0 ]
then
    rm -f build-script build-script-header
    exit 0
fi

# check md5
SCRIPT_MD5="`md5sum <build-script`"
HEADER_MD5="`fgrep Content-MD5: build-script-header`"

if [ "${SCRIPT_MD5:0:32}" != "${HEADER_MD5: -32}" ]
then
    # something is wrong, but don't bother to log it or anything
    rm -f build-script build-script-header
    exit 0
fi

JOB_ID="`fgrep X-Job-ID: build-script-header`"
JOB_ID="${JOB_ID#*X-Job-ID: }"

# insure build dir is clean
rm -rf build-dir 
mkdir build-dir
cd build-dir

STATUS="fail"
if sh ../build-script > build-script-output 2>&1
then
    echo "sh returned $? - OK" >>$LOG
	STATUS="ok"
else
    echo "sh returned $? - fail" >>$LOG
fi

RESULT="result-$$.tgz"

echo "Creating archive jobid=$JOB_ID agentid=$AGENTID status=$STATUS" >>$LOG
tar cvfz ../$RESULT . >>$LOG 2>&1

cd ..
# now that archive is build, remove the build-dir and script
# so another job can start while upload continues
rm -rf build-dir build-script build-script-header

echo "Uploading `ls -lh $RESULT`" >>$LOG
curl -q -F "userfile=@$RESULT" -F "jobid=$JOB_ID" -F "agentid=$AGENTID" -F "status=$STATUS" http://build.pennyos.org/result.php >>$LOG 2>&1
echo "COMPLETED upload rc=$? - ready for next job" >>$LOG

rm -f $RESULT

